version: '3.1'

services:
  my-1finances-backend:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
